services:
  wordpress:
    image: wordpress:php8.1
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "${WP_PORT:-80}:80"
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER: username
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_HOME', 'http://' . ($$_SERVER['HTTP_HOST'] ?? 'localhost') );
        define( 'WP_SITEURL', 'http://' . ($$_SERVER['HTTP_HOST'] ?? 'localhost') );
    volumes:
      - .:/var/www/html

  wp-cli:
    image: wordpress:cli
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER: username
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_HOME', 'http://' . ($$_SERVER['HTTP_HOST'] ?? 'localhost') );
        define( 'WP_SITEURL', 'http://' . ($$_SERVER['HTTP_HOST'] ?? 'localhost') );
    volumes:
      - .:/var/www/html

  database:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    volumes:
      - database:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "${PMA_PORT:-8888}:80"
    environment:
      PMA_HOST: database
      UPLOAD_LIMIT: 1G

volumes:
  database:
