version: "3.7"
services:

  nginx:
    image: nginx
    volumes:
      - ./docker-nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - php

  mysql:
    image: mariadb
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password

  php:
    build: .
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql

volumes:
  mysql-data:
